[build-system]
requires = [
  "hatchling",
  "hatch-requirements-txt",
  "hatch-fancy-pypi-readme>=22.5.0",
]
build-backend = "hatchling.build"

[project]
name = "gradio-pyvistaplotter"
dynamic = ["version"]
description = "Gradio PyVista Viewer"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
authors = [{ name = "Louis Pujol"}]
keywords = ["gradio-custom-component", "gradio-template-HTML"]
# Add dependencies here
dependencies = ["gradio>=6.0,<7.0", "pyvista[jupyter]"]
classifiers = [
  'Development Status :: 3 - Alpha',
  'Operating System :: OS Independent',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3 :: Only',
  'Programming Language :: Python :: 3.10',
  'Programming Language :: Python :: 3.11',
  'Programming Language :: Python :: 3.12',
  'Programming Language :: Python :: 3.13',
  'Topic :: Scientific/Engineering',
  'Topic :: Scientific/Engineering :: Artificial Intelligence',
  'Topic :: Scientific/Engineering :: Visualization',
]


[project.optional-dependencies]
dev = ["pre-commit", "build", "twine"]

[project.urls]
repository = "https://github.com/Louis-Pujol/gradio-pyvistaplotter"
space = "https://huggingface.co/spaces/Louis-Pujol/gradio-pyvistaplotter"

[tool.hatch.build]
artifacts = ["backend/gradio_pyvistaplotter/static", "*.pyi"]

[tool.hatch.build.targets.wheel]
packages = ["backend/gradio_pyvistaplotter"]

[tool.hatch.version]
path = "backend/gradio_pyvistaplotter/__init__.py"

# See: https://learn.scientific-python.org/development/guides/style/#PC190
[tool.ruff]
line-length = 79

[tool.ruff.lint]
extend-select = [
	"B",        # flake8-bugbear
	"I",        # isort
	"ARG",      # flake8-unused-arguments
	"C4",       # flake8-comprehensions
	"EM",       # flake8-errmsg
	"ICN",      # flake8-import-conventions
	"G",        # flake8-logging-format
	"PGH",      # pygrep-hooks
	"PIE",      # flake8-pie
	"PL",       # pylint
	"PT",       # flake8-pytest-style
	"PTH",      # flake8-use-pathlib
	"RET",      # flake8-return
	"RUF",      # Ruff-specific
	"SIM",      # flake8-simplify
	"T20",      # flake8-print
	"UP",       # pyupgrade
	"YTT",      # flake8-2020
	"EXE",      # flake8-executable
	"NPY",      # NumPy specific rules
	"FURB",     # refurb
	"PYI",      # flake8-pyi
]


[tool.ruff.format]
indent-style = "space"
docstring-code-format = true
